### ISSUE TITLE
[📝 DOCS] Create CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Maghish** [StarReach/Pluto#6]
We need to create CODE_OF_CONDUCT.md for this project as well. This issue is pretty self-explanatory so I don't need to provide much information 

- [x] I have checked all issues and found no duplicates of this issue
- [x] I can resolve this issue by myself
- [x] This documentation update request is authorized by the admins or moderators of this repository *(if anyone found that you lied that this documentation update request is authorized by the admins or moderators then you will be punished)*

**Comment by NanotechPikachu** [comment]
## COMPLETED
