### ISSUE TITLE
[📝 DOCS] Create Contributing.md

### ISSUE THREAD

**Issue by Maghish** [StarReach/Pluto#7]
We need to create Contributing.md to this project as well. This issue is pretty self-explanatory just like issue #6, we don't need much information

- [x] I have checked all issues and found no duplicates of this issue
- [x] I can resolve this issue by myself
- [x] This documentation update request is authorized by the admins or moderators of this repository *(if anyone found that you lied that this documentation update request is authorized by the admins or moderators then you will be punished)*

**Comment by NanotechPikachu** [comment]
You mean like contributor guidelines?

**Comment by Maghish** [comment]
Yeah I'm pretty sure we made one in the old pluto repo right?

**Comment by NanotechPikachu** [comment]
## COMPLETED

**Credits for source**: @Maghish

**Comment by Maghish** [comment]
Fr?
